export {default as Submitbtn} from './SubmitBtn'
export {default as FormInput} from './FormInput'
export {default as Header} from './Header'
export {default as Hero} from './Hero'
export {default as Navbar} from './Navbar'
export { default as FeaturedProducts } from './FeaturedProducts'
export { default as SectionTitle } from './SectionTitle'